version: '3.7'
services:
  # Admin UI: http://localhost:18080/auth/admin/master/console/
  # Login: admin/keycloak
  # Account console: http://localhost:18080/auth/realms/fwu/account/
  # Login: misty/test
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.4.2
    ports:
      - 18080:8080
      - 8787:8787
    restart: always
    environment:
      KC_HTTP_RELATIVE_PATH: "/auth"
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: keycloak
      KC_DB_URL_HOST: postgres
      KC_DB: postgres
      KC_DB_USER: keycloak
      KC_DB_PASSWORD: password
      KC_SPI_AUTHENTICATOR_WHITELIST_AUTHENTICATOR_KC_AUTH_URL: http://localhost:8080/auth
      KC_SPI_AUTHENTICATOR_WHITELIST_AUTHENTICATOR_REST_URL: http://mockserver:1080/service-provider/%s/idp-assignments
      KC_SPI_AUTHENTICATOR_SCHOOL_WHITELIST_AUTHENTICATOR_KC_AUTH_URL: http://localhost:8080/auth
      KC_SPI_AUTHENTICATOR_SCHOOL_WHITELIST_AUTHENTICATOR_REST_URL: http://mockserver:1080/school-assignments
      KC_SPI_EVENTS_LISTENER_LOGIN_EVENT_PUBLISHER_RMQ_HOST: test-rabbitmq
      KC_SPI_EVENTS_LISTENER_LOGIN_EVENT_PUBLISHER_RMQ_PORT: 5672
      KC_SPI_EVENTS_LISTENER_LOGIN_EVENT_PUBLISHER_RMQ_EXCHANGE: login-details
      KC_SPI_EVENTS_LISTENER_LOGIN_EVENT_PUBLISHER_RMQ_USERNAME: guest
      KC_SPI_EVENTS_LISTENER_LOGIN_EVENT_PUBLISHER_RMQ_PASSWORD: guest
      KC_SPI_EVENTS_LISTENER_LOGIN_EVENT_PUBLISHER_SCHOOLIDS_ATTRIBUTE: prefixedSchools
      KC_SPI_EVENTS_LISTENER_LOGIN_EVENT_PUBLISHER_BMI_RMQ_HOST: test-rabbitmq
      KC_SPI_EVENTS_LISTENER_LOGIN_EVENT_PUBLISHER_BMI_RMQ_PORT: 5672
      KC_SPI_EVENTS_LISTENER_LOGIN_EVENT_PUBLISHER_BMI_RMQ_EXCHANGE: login-details
      KC_SPI_EVENTS_LISTENER_LOGIN_EVENT_PUBLISHER_BMI_RMQ_USERNAME: guest
      KC_SPI_EVENTS_LISTENER_LOGIN_EVENT_PUBLISHER_BMI_RMQ_PASSWORD: guest
      KC_SPI_EVENTS_LISTENER_LOGIN_EVENT_PUBLISHER_BMI_SCHOOLIDS_ATTRIBUTE: prefixedSchools
      KC_SPI_ADMIN_REALM_RESTAPI_EXTENSION_HMAC_VERIFIER_REALM: fwu
      KC_SPI_ADMIN_REALM_RESTAPI_EXTENSION_HMAC_MANAGEMENT_REALM: management
      KC_SPI_EVENTS_LISTENER_REMOVE_USER_ON_LOGOUT_FWU: "IDP"
      KC_SPI_REST_CLIENT_DEFAULT_LICENCE_CONNECT_BASE_URL: http://mockserver:1080
      KC_SPI_REST_CLIENT_DEFAULT_LICENCE_CONNECT_API_KEY: sample-api-key
      KC_SPI_ADMIN_REALM_RESTAPI_EXTENSION_VIDIS_CUSTOM_FWU: "ALL"
      KC_SPI_ADMIN_REALM_RESTAPI_EXTENSION_VIDIS_CUSTOM_DELETIONTOLERANCE: 5
      KC_FEATURES: admin-api
      DEBUG: "true"
      DEBUG_PORT: "8787"
    command: [ "start-dev", "--import-realm", "--spi-theme-static-max-age=-1", "--spi-theme-cache-themes=false", "--spi-theme-cache-templates=false" ]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #    - realms
      - "./test/fwu-realm.json:/opt/keycloak/data/import/fwu-realm.json"
      - "./test/whitelist_realm.json:/opt/keycloak/data/import/whitelist_realm.json"
      - "./test/idp-realm.json:/opt/keycloak/data/import/idp-realm.json"
      - "./test/idp2_realm.json:/opt/keycloak/data/import/idp2_realm.json"
      - "./test/management-realm.json:/opt/keycloak/data/import/management-realm.json"
      #    - themes
      #      - "../keycloak-themes/fwu-base-theme:/opt/keycloak/themes/fwu-base-theme"
      #      - "../keycloak-themes/fwu-idp-theme:/opt/keycloak/themes/fwu-idp-theme"
      #      - "../keycloak-themes/fwu-vidis-button-theme:/opt/keycloak/themes/fwu-vidis-button-theme"
      #      - "../keycloak-themes/fwu-vidis-theme:/opt/keycloak/themes/fwu-vidis-theme"
      #    - extensions
      - "./target:/opt/keycloak/providers/"
      - "./test/lib/keycloak-custom-attribute-idp-linking-2.1.0.jar:/opt/keycloak/providers/keycloak-custom-attribute-idp-linking-2.1.0.jar"
    networks:
      - fwunet
    depends_on:
      - idp_mock
      - postgres
      - rabbitmq

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - ./test/pg-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_MULTIPLE_DATABASES: keycloak,iam,logindetails
      POSTGRES_PASSWORD: password
    networks:
      - fwunet

  idp_mock:
    container_name: idp-mock
    image: ghcr.io/navikt/mock-oauth2-server:0.5.1
    ports:
      - 8443:8080
    networks:
      - fwunet

  saml_idp:
    container_name: saml-idp-mock
    image: quay.io/keycloak/keycloak:22.0.4
    ports:
      - 18443:8080
    environment:
      KC_HTTP_RELATIVE_PATH: "/auth"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: keycloak
    command: [ "start-dev", "--import-realm" ]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./test/saml-realm.json:/opt/keycloak/data/import/saml-realm.json
    networks:
      - fwunet

  mockServer:
    image: mockserver/mockserver:5.14.0
    container_name: mockserver
    command: -logLevel DEBUG
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/mockserver.json
    ports:
      - 11090:1080
    volumes:
      - ./test/mock/mockserver.json:/config/mockserver.json
    networks:
      - fwunet

  # Admin UI: http://localhost:15672/
  # Login: guest/guest
  rabbitmq:
    image: rabbitmq:3-management
    container_name: test-rabbitmq
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./test/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./test/rabbitmqdefinitions.json:/etc/rabbitmq/rabbitmqdefinitions.json:ro
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - fwunet

networks:
  fwunet:
    driver: bridge
    ipam:
      driver: default
