name: "Test feature"
on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Check release exists
        id: check-release
        run: |
          TAG=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)
          response=$(curl -H 'Accept: application/vnd.github.v3+json' https://api.github.com/repos/FWU-DE/fwu-kc-extensions/releases/tags/$TAG)
          message=$(echo $response | jq -r .message)
          if [ "$message" == "Not Found" ]; then
            echo "::set-output name=version::$TAG"
            modules=$(mvn -Dexec.executable='echo' -Dexec.args='${project.artifactId}' exec:exec -q)
            for module in $modules
            do
              if [ "$module" != "fwu-kc-extensions" ]; then
                echo "$module/target/$module-$TAG.jar" >> modules.txt
              fi
            done
            csv=$(paste -s -d , modules.txt)
            echo "::set-output name=artifacts::$csv"
          else
            echo "Release $TAG already exists!"
          fi
      - name: Publish release
        if: ${{ steps.check-release.outputs.version != '' }}
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.check-release.outputs.version }}
          artifacts: ${{ steps.check-release.outputs.artifacts }}
          bodyFile: "CHANGELOG.md"
          token: ${{ secrets.GITHUB_TOKEN }}
