name: "Test feature"
on:
  push:
    branches-ignore:
      - main
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Start test containers
        run: docker compose -f user-licence-lifecycle-manager/src/test/resources/docker-compose.yaml up --detach
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
