name: "Release snapshot"
on:
  push:
    tags:
      - '*-SNAPSHOT'

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn --batch-mode package -DprojectVersion=$GITHUB_REF_NAME

  publish:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Get module names
        id: get-modules
        run: |
          mvn -Dexec.executable='echo' -Dexec.args='${project.artifactId}' -DprojectVersion=$GITHUB_REF_NAME exec:exec -q
          modules=$(mvn -Dexec.executable='echo' -Dexec.args='${project.artifactId}' -DprojectVersion=$GITHUB_REF_NAME exec:exec -q)
          echo "modules=$modules" >> $GITHUB_ENV
          for module in $modules
          do
            if [ "$module" != "fwu-kc-extensions" ]; then
              echo "$module/target/$module-$GITHUB_REF_NAME.jar" >> modules.txt
            fi
          done
          cat modules.txt >> $GITHUB_ENV
          csv=$(paste -s -d , modules.txt)
          echo "artifacts=$csv" >> $GITHUB_OUTPUT
      - name: Build with Maven
        if: ${{ steps.get-modules.outputs.version != '' }}
        run: mvn --batch-mode clean deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish release
        if: ${{ steps.get-modules.outputs.version != '' }}
        uses: ncipollo/release-action@v1
        with:
          tag: $GITHUB_REF_NAME
          artifacts: "${{ steps.get-modules.outputs.artifacts }}"
          bodyFile: "CHANGELOG.md"
          token: ${{ secrets.GITHUB_TOKEN }}
