name: "Release snapshot"
on:
  push:
    tags:
      - '*-SNAPSHOT'

jobs:
  publish:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Deploy to GitHub packages
        run: mvn --batch-mode deploy -Drevision=$GITHUB_REF_NAME -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get maven group
        id: get-group
        uses: mavrosxristoforos/get-xml-info@1.0
        with:
          xml-file: 'pom.xml'
          xpath: "//*[local-name()='project']/*[local-name()='groupId']"
      - name: Get modules
        id: get-modules
        uses: mavrosxristoforos/get-xml-info@1.0
        with:
          xml-file: 'pom.xml'
          xpath: "//*[local-name()='project']/*[local-name()='modules']/*[local-name()='module']"
      - name: Get artifacts
        id: get-artifacts
        run: |
          echo "version=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT
          IFS="," read -ra modules <<< ${{ steps.get-modules.outputs.info }}
          for module in ${modules[@]}
          do
            if [ "$module" != "fwu-kc-extensions" ]; then
              echo "$module/target/$module-$GITHUB_REF_NAME.jar" >> modules.txt
            fi
          done
          csv=$(paste -s -d , modules.txt)
          echo "artifacts=$csv" >> $GITHUB_OUTPUT
      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.get-artifacts.outputs.version }}
          artifacts: "${{ steps.get-artifacts.outputs.artifacts }}"
          bodyFile: "CHANGELOG.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          allowUpdates: true
      - name: Publish to gitlab
        env:
          GITLAB_HOST: ${{ secrets.GITLAB_HOST }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GITLAB_PROJECT_ID: ${{ secrets.GITLAB_PROJECT_ID  }}
          ARTIFACTS: "${{ steps.get-artifacts.outputs.artifacts }}"
          GROUP_NAME: ${{ steps.get-group.outputs.info }}
          VERSION: $GITHUB_REF_NAME
        run: |
          group=${GROUP_NAME/.//}
          echo "group: ${group}"
          IFS=',' read -ra archives <<< $ARTIFACTS
          for archive in ${archives[@]}
          do
              filename=${archive##*/}
              artifact=${filename%-*}
              url="https://${GITLAB_HOST}/api/v4/projects/${GITLAB_PROJECT_ID}/packages/maven/${group}/${artifact}/${VERSION}/${filename}"
              echo "Uploading ${archive} to ${url}" 
              curl --fail --request PUT \
                  --upload-file ${archive} \
                  --header "Deploy-Token: ${GITLAB_TOKEN}" \
                  ${url}
          done
